spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver # 数据库驱动
    username: test # 数据库用户名
    password: 123456 # 数据库密码
    url: jdbc:mysql://118.126.110.110:3306/healthy?characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8 # 数据库链接
  jackson:
    default-property-inclusion: non_null # JSON输出不能空
  redis:
    host: 118.126.110.110 # Redis域名
    port: 6379 # Redis端口
    password: 123456 # Redis密码
  servlet:
    multipart:
      max-file-size: 5MB # 单个文件最大大小
      max-request-size: 50MB # 请求的总最大大小
  resources:
    static-locations: file:img/,classpath:/static/ # 静态资源路径
  freemarker:
    suffix: .html # freemarker后缀名
server:
  port: 9004 # tomcat服务器端口
#  servlet:
#    context-path: /healthy # 项目环境上下文变量
logging:
  level:
    com.cdutcm.healthy.dataobject.mapper: debug # 显示SQL语句
    com.baomidou.mybatisplus.extension.service: debug # 显示SQL语句
    io.swagger.models.parameters.AbstractSerializableParameter: error # Swagger2
healthy:
  wechat:
    mpAppId: wx2b0ee4947389c1cb # 微信Appid
    mpAppSecret: 8fefb4a2a6e448255408d0fb2bfffafa # 微信Secret
    token: wyy # 微信token
    templateId:
      bodyIndex: etyOZEgzBlYSo1spAIdFD4lNXJvG_cAPihQqTqbIDCE #微信模板消息ID
  url:
    wechatMpAuthorize: http://api.healthy.tuyrk.cn # 微信授权地址
    returnUrl: http://healthy.tuyrk.cn # 登录跳转首页
    perfectUrl: http://healthy.tuyrk.cn/#/personalCenter/bodyInfo?login=true # 完善用户信息页面地址
    adminLogin: http://admin.healthy.tuyrk.cn # 管理员登录地址
    healthy: http://api.healthy.tuyrk.cn # 项目地址
    domain: api.healthy.tuyrk.cn
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml